kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
            #slack_api_url: 'https://hooks.slack.com/services/TH2HF4PT5/
    templates:
        - '/etc/alertmanager/slack.tmpl'
    route:
      receiver: slack_demo
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
        - match:
            severity: slack
          group_wait: 10s
          repeat_interval: 15m

    receivers:
    - name: slack_demo
      slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: 'notifications'
